# Generated by Django 4.2.1 on 2023-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_prefer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prefer_location',
        ),
        migrations.AlterField(
            model_name='user',
            name='prefer_distance_min',
            field=models.IntegerField(default=1),
        ),
    ]
